[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@foundry-devops/src=lib/foundry-devops/src/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/",
    "@ccip/=lib/ccip/contracts",
    "@chainlink-local/=lib/chainlink-local/"
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arb-sepolia = "${ARB_SEPOLIA_RPC_URL}"


[invariant]
runs = 256
depth = 256
fail_on_revert = true